### These requests can be used to test the REST API using the REST Client Extention in VS Code

### Login using credentials
POST HTTP://localhost:5000/login
Content-Type: application/json

{
    "username":"Fulan.Fulani",
    "password":"asdfqasdf"
}

### generate a new access token using the refresh token
POST HTTP://localhost:5000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFIRjQyTllNRDU3SzdXNEJESDg0WUs1WlAiLCJ1c2VybmFtZSI6IkZ1bGFuLkZ1bGFuaSIsImlhdCI6MTY5OTg4MjA2OSwiZXhwIjoxNjk5ODgyMTg5fQ.rutDRDPMaOxzMpMFn7ngm8rIXGAn2KWhV6QfjqWs28g"
}

### logout by deleting the refresh token from the approved token list
DELETE HTTP://localhost:5000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFIRjQyTllNRDU3SzdXNEJESDg0WUs1WlAiLCJ1c2VybmFtZSI6IkZ1bGFuLkZ1bGFuaSIsImlhdCI6MTY5OTg4MjA2OSwiZXhwIjoxNjk5ODgyMTg5fQ.rutDRDPMaOxzMpMFn7ngm8rIXGAn2KWhV6QfjqWs28g"
}


### get task list for each user. works only if user is authenticated already. Request must include a valid access token
GET HTTP://localhost:5000/getUserTaskList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFIRjQyTllNRDU3SzdXNEJESDg0WUs1WlAiLCJ1c2VybmFtZSI6IkZ1bGFuLkZ1bGFuaSIsImlhdCI6MTY5OTg4MjA2OSwiZXhwIjoxNjk5ODgyMTI5fQ.p0Yew0MaIvOShiFqI2gmmPWmQAmEH0DR_Z85ZVJcH28